package model;
// Generated Apr 2, 2018 9:42:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name = "korisnik", catalog = "telecomdb")
public class Korisnik implements java.io.Serializable {

	private Integer id;
	private String ime;
	private String prezime;
	private Date datumRodjenja;
	private Integer admin;
	private Integer superAdmin;

	public Korisnik() {
	}

	public Korisnik(String ime, String prezime, Date datumRodjenja, Integer admin, Integer superAdmin) {
		this.ime = ime;
		this.prezime = prezime;
		this.datumRodjenja = datumRodjenja;
		this.admin = admin;
		this.superAdmin = superAdmin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ime", length = 50)
	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	@Column(name = "prezime", length = 50)
	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datumRodjenja", length = 10)
	public Date getDatumRodjenja() {
		return this.datumRodjenja;
	}

	public void setDatumRodjenja(Date datumRodjenja) {
		this.datumRodjenja = datumRodjenja;
	}

	@Column(name = "admin")
	public Integer getAdmin() {
		return this.admin;
	}

	public void setAdmin(Integer admin) {
		this.admin = admin;
	}

	@Column(name = "superAdmin")
	public Integer getSuperAdmin() {
		return this.superAdmin;
	}

	public void setSuperAdmin(Integer superAdmin) {
		this.superAdmin = superAdmin;
	}

}
