package model;
// Generated Apr 2, 2018 9:42:01 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "telecomdb")
public class Login implements java.io.Serializable {

	private String username;
	private String password;
	private int korisnikId;

	public Login() {
	}

	public Login(String username, String password, int korisnikId) {
		this.username = username;
		this.password = password;
		this.korisnikId = korisnikId;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "korisnikId", nullable = false)
	public int getKorisnikId() {
		return this.korisnikId;
	}

	public void setKorisnikId(int korisnikId) {
		this.korisnikId = korisnikId;
	}

}
