package model;
// Generated Apr 2, 2018 9:42:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prekidzahtjeva generated by hbm2java
 */
@Entity
@Table(name = "prekidzahtjeva", catalog = "telecomdb")
public class Prekidzahtjeva implements java.io.Serializable {

	private Integer id;
	private Date datumPrekida;
	private int zahtjevId;

	public Prekidzahtjeva() {
	}

	public Prekidzahtjeva(Date datumPrekida, int zahtjevId) {
		this.datumPrekida = datumPrekida;
		this.zahtjevId = zahtjevId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datumPrekida", nullable = false, length = 10)
	public Date getDatumPrekida() {
		return this.datumPrekida;
	}

	public void setDatumPrekida(Date datumPrekida) {
		this.datumPrekida = datumPrekida;
	}

	@Column(name = "zahtjevId", nullable = false)
	public int getZahtjevId() {
		return this.zahtjevId;
	}

	public void setZahtjevId(int zahtjevId) {
		this.zahtjevId = zahtjevId;
	}

}
