package model;
// Generated Apr 2, 2018 9:42:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rezultatproblema generated by hbm2java
 */
@Entity
@Table(name = "rezultatproblema", catalog = "telecomdb")
public class Rezultatproblema implements java.io.Serializable {

	private Integer id;
	private Date datumZavrsetka;
	private String objasnjenje;
	private int problemId;

	public Rezultatproblema() {
	}

	public Rezultatproblema(int problemId) {
		this.problemId = problemId;
	}

	public Rezultatproblema(Date datumZavrsetka, String objasnjenje, int problemId) {
		this.datumZavrsetka = datumZavrsetka;
		this.objasnjenje = objasnjenje;
		this.problemId = problemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datumZavrsetka", length = 10)
	public Date getDatumZavrsetka() {
		return this.datumZavrsetka;
	}

	public void setDatumZavrsetka(Date datumZavrsetka) {
		this.datumZavrsetka = datumZavrsetka;
	}

	@Column(name = "objasnjenje", length = 50)
	public String getObjasnjenje() {
		return this.objasnjenje;
	}

	public void setObjasnjenje(String objasnjenje) {
		this.objasnjenje = objasnjenje;
	}

	@Column(name = "problemId", nullable = false)
	public int getProblemId() {
		return this.problemId;
	}

	public void setProblemId(int problemId) {
		this.problemId = problemId;
	}

}
