package model;
// Generated Apr 2, 2018 9:42:01 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usluga generated by hbm2java
 */
@Entity
@Table(name = "usluga", catalog = "telecomdb")
public class Usluga implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private Double cijena;

	public Usluga() {
	}

	public Usluga(String naziv, Double cijena) {
		this.naziv = naziv;
		this.cijena = cijena;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naziv", length = 50)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "cijena", precision = 22, scale = 0)
	public Double getCijena() {
		return this.cijena;
	}

	public void setCijena(Double cijena) {
		this.cijena = cijena;
	}

}
