package model;
// Generated Apr 2, 2018 9:42:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zahtjev generated by hbm2java
 */
@Entity
@Table(name = "zahtjev", catalog = "telecomdb")
public class Zahtjev implements java.io.Serializable {

	private Integer id;
	private Date datumPodnosenja;
	private int korisnikId;
	private int uslugaId;
	private String statusZahtjeva;

	public Zahtjev() {
	}

	public Zahtjev(int korisnikId, int uslugaId) {
		this.korisnikId = korisnikId;
		this.uslugaId = uslugaId;
	}

	public Zahtjev(Date datumPodnosenja, int korisnikId, int uslugaId, String statusZahtjeva) {
		this.datumPodnosenja = datumPodnosenja;
		this.korisnikId = korisnikId;
		this.uslugaId = uslugaId;
		this.statusZahtjeva = statusZahtjeva;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datumPodnosenja", length = 10)
	public Date getDatumPodnosenja() {
		return this.datumPodnosenja;
	}

	public void setDatumPodnosenja(Date datumPodnosenja) {
		this.datumPodnosenja = datumPodnosenja;
	}

	@Column(name = "korisnikId", nullable = false)
	public int getKorisnikId() {
		return this.korisnikId;
	}

	public void setKorisnikId(int korisnikId) {
		this.korisnikId = korisnikId;
	}

	@Column(name = "uslugaId", nullable = false)
	public int getUslugaId() {
		return this.uslugaId;
	}

	public void setUslugaId(int uslugaId) {
		this.uslugaId = uslugaId;
	}

	@Column(name = "statusZahtjeva", length = 50)
	public String getStatusZahtjeva() {
		return this.statusZahtjeva;
	}

	public void setStatusZahtjeva(String statusZahtjeva) {
		this.statusZahtjeva = statusZahtjeva;
	}

}
